#!/bin/bash

APPLICATION_PORT=8000
APPLICATION_VERSION=0.0.1-SNAPSHOT
APPLICATION_NAME="backend"
APPLICATION_FULL_NAME="$APPLICATION_NAME-$APPLICATION_VERSION"
APPLICATION_PATH="./target/$APPLICATION_FULL_NAME.jar"
PID_PATH="./$APPLICATION_NAME.pid" # process identification number
OUTPUT_PATH="/var/log/$APPLICATION_NAME.log" # output
